name: Deploy Minecraft Mod

description: Builds and deploys a Minecraft mod to GitHub releases

inputs:
  token:
    description: "GitHub Token"
    required: true
  java-version:
    description: "Java version"
    required: false
    default: 17
  gradle-version:
    description: "Gradle version"
    required: false
    default: current

runs:
  using: composite

  steps:
    - name: Setup Environment
      shell: bash
      run: |
        echo "VERSION=${GITHUB_REF//refs\/tags\/v}" >> $GITHUB_ENV

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ inputs.java-version }}

    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: ${{ inputs.gradle-version }}
        arguments: build

    - name: Publish to GitHub Releases
      uses: AButler/upload-release-assets@v2.0
      with:
        files: build/libs/*-${{ env.VERSION }}.jar
        repo-token: ${{ inputs.token }}
        release-tag: ${{ env.RELEASE_TAG }}
